### ISSUE TITLE
Docker: static files : 404 

### ISSUE THREAD

**Issue by garanews** [stratosphereips/Manati#13]
nginx_1     | 1.2.3.4 - - [27/Nov/2017:15:45:46 +0000] "GET /static/manati_ui/js/libs/mousetrap.min.js HTTP/1.1" 404 169 "http://5.6.7.8:8080/manati_project/manati_ui/analysis_session/new" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0" "-

**Comment by Piuliss** [comment]
Thanks. I will take a look. !

**Comment by garanews** [comment]
I need to fix it before try the "normal work" :)

![image](https://user-images.githubusercontent.com/16938405/33311900-88b63926-d426-11e7-847b-e38673db1ecc.png)

**Comment by Piuliss** [comment]
<img width="1069" alt="screen shot 2017-11-28 at 10 29 22 am" src="https://user-images.githubusercontent.com/1384962/33312143-48a71368-d427-11e7-87a1-1e7670205910.png">

I have checked the directory and the JS library it is there. 

Your image is showing that all the CSS/JS libraries are not there, probably this command 
`python manage.py collectstatic` is missing

However, when you execute `docker-compose up`, it should execute it.  in the docker-composer.yml

**Comment by garanews** [comment]
rq_1        | 11:01:37 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
web_1       | Operations to perform:
web_1       |   Apply all migrations: manati_ui, userena, sessions, admin, guardian, sites, auth, contenttypes, api_manager, easy_thumbnails, user_profiles
web_1       | Running migrations:
web_1       |   No migrations to apply.
web_1       |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
web_1       |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
web_1       | Debug is enabled.
web_1       | ######################################################
web_1       | Starting tp register new External Modules ....
web_1       | Finished registering new External Modules succeed
web_1       | ######################################################
web_1       | ######################################################
web_1       | Starting to check  external modules ....
web_1       | Information of Module: bulk_find_whois is checked
web_1       | Information of Module: bulk_labeling is checked
web_1       | Information of Module: whois_relation_req is checked
web_1       | Finished to check External Modules succeed
web_1       | ######################################################
web_1       | Debug is enabled.
web_1       |
web_1       | You have requested to collect static files at the destination
web_1       | location as specified in your settings:
web_1       |
web_1       |     /code/static
web_1       |
web_1       | This will overwrite existing files!
web_1       | Are you sure you want to do this?
web_1       |
web_1       | Type 'yes' to continue, or 'no' to cancel: Traceback (most recent call last):
web_1       |   File "manage.py", line 31, in <module>
web_1       |     execute_from_command_line(sys.argv)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
web_1       |     utility.execute()
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
web_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
web_1       |     self.execute(*args, **cmd_options)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
web_1       |     output = self.handle(*args, **options)
web_1       |   File "/usr/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle
web_1       |     if self.interactive and input(''.join(message)) != 'yes':
web_1       | EOFError: EOF when reading a line
manati_web_1 exited with code 1

**Comment by garanews** [comment]
Docker version 17.05.0-ce, build 89658be
docker-compose version 1.10.0, build 4bd6f1a

**Comment by garanews** [comment]
I see the web.conf under/etc/nginx/conf.d that says:
    location /static/ {
        alias /static/;
    }

Should I provide a volume to ngix container where the static files are locared?

**Comment by Piuliss** [comment]
I think the docker it is not the problem. 
docker-compose version 1.14.0, build c7bdf9e
Docker version 17.06.1-ce, build 874a737

The error is because is missing "--noinput", I mean, it is asking for an answer and it is skipped it. So, it is necessary to put it back. 

We are not using volumes for statics files. 
But you can try adding a new volumen in the volumes section. 
**docker-compose.yml**
```
web:
    build: '.'
    image: 'manati'
    env_file:
      - '.env'
      - '.env-docker'
    expose:
      - "8000"
    ports:
      - '127.0.0.1:8000:8000'
    command: 'bash -c "python manage.py migrate && python manage.py check_external_modules && python manage.py collectstatic --noinput && gunicorn manati.wsgi:application -w 2 -b :8000 --capture-output --enable-stdio-inheritance --log-level=debug --access-logfile=- --log-file=-"'
    volumes:
      - '.:/code'
      - 'manati_cachedata:/cache'
      - 'manati_mediadata:/media'
      - 'manati_static:/static'
```
and in **web.conf** replace for:

```
location /static/ {
alias /code/static/;
}
```
